<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-07T15:34:46 IST" name="Default suite" finished-at="2023-10-07T15:34:46 IST" duration-ms="145">
    <groups>
    </groups>
    <test started-at="2023-10-07T15:34:46 IST" name="Default test" finished-at="2023-10-07T15:34:46 IST" duration-ms="145">
      <class name="newselenium.EdubridgeProject">
        <test-method is-config="true" signature="start()[pri:0, instance:newselenium.EdubridgeProject@350aac89]" started-at="2023-10-07T15:34:46 IST" name="start" finished-at="2023-10-07T15:34:46 IST" duration-ms="39" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method signature="pro([Ljava.lang.String;)[pri:0, instance:newselenium.EdubridgeProject@350aac89]" started-at="2023-10-07T15:34:46 IST" name="pro" finished-at="2023-10-07T15:34:46 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void newselenium.EdubridgeProject.pro(java.lang.String[]) throws java.lang.InterruptedException,java.io.IOException requires a @DataProvider named : getData in class newselenium.DataUtils]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void newselenium.EdubridgeProject.pro(java.lang.String[]) throws java.lang.InterruptedException,java.io.IOException requires a @DataProvider named : getData in class newselenium.DataUtils
at org.testng.internal.Parameters.findDataProvider(Parameters.java:526)
at org.testng.internal.Parameters.handleParameters(Parameters.java:763)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:911)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pro -->
        <test-method is-config="true" signature="end()[pri:0, instance:newselenium.EdubridgeProject@350aac89]" started-at="2023-10-07T15:34:47 IST" name="end" finished-at="2023-10-07T15:34:47 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- newselenium.EdubridgeProject -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
